blank_issues_enabled: false

issue_templates:
  - name: âœ¨ ê¸°ëŠ¥ ê°œë°œ ì´ìŠˆ
    description: ê¸°ëŠ¥ êµ¬í˜„ ë° ì»´í¬ë„ŒíŠ¸ ê°œë°œ ì‘ì—…ì„ ìœ„í•œ í…œí”Œë¦¿
    file: feat-template.md
    labels:
      - feature
    assignees: []

  - name: âš¡ï¸ ë²„ê·¸ ë¦¬í¬íŠ¸
    description: ë°œê²¬ëœ ë²„ê·¸ë¥¼ ìƒì„¸íˆ ë³´ê³ í•˜ê³  ì¶”ì í•©ë‹ˆë‹¤.
    file: bug-report.md
    labels:
      - bug
    assignees: []

  - name: ğŸ–‹ï¸ ë¬¸ì„œ ìˆ˜ì • ìš”ì²­
    description: README, ë¬¸ì„œ, ì£¼ì„ ë“±ì— ëŒ€í•œ ìˆ˜ì • ì‚¬í•­ì„ ìš”ì²­í•©ë‹ˆë‹¤.
    file: docs-update.md
    labels:
      - documentation
    assignees: []

  - name: ğŸ‹ï¸ ë¦¬íŒ©í† ë§ ìš”ì²­
    description: ì½”ë“œ êµ¬ì¡° ê°œì„ ì´ë‚˜ ë¦¬íŒ©í† ë§ ìš”ì²­ì„ ìƒì„±í•©ë‹ˆë‹¤.
    file: refactor-request.md
    labels:
      - refactor
    assignees: []
